### ISSUE TITLE
[Question] Continuous variables

### ISSUE THREAD

**Issue by JovanVeljanoski** [spotify/confidence#60]
Hi! 

This is a great package - thank you for sharing it with the community!

A quick question: is there a plan for adding methods for testing continuous variables?

Thanks!

**Comment by iampelle** [comment]
Hi!

At Spotify we use it to compare averages of continuous variables all the time (e.g. consumption time), either using the ZTest or the StudentTTest class (the latter gives more power if you have less than a few hundred samples, otherwise it doesn't make much of a difference which you use). This works because the sample distribution of the mean of a continuous variable will be normally distributed (as long as the variance is finite) according to [central limit theorem](https://en.wikipedia.org/wiki/Central_limit_theorem).

**Comment by iampelle** [comment]
On the Bayesian side we only have support for variables Binomial likelihood. We don't use Bayesian analysis that much at Spotify and will probably not add support for e.g. variables with Normal likelihood, but community contributions are much welcome! 🙂

**Comment by JovanVeljanoski** [comment]
Hi, 

Thank you for the response and for the insights - very useful. And again, thank you for open-sourcing this!

Cheers, 
J.

**Comment by LibiSC** [comment]
sorry for commenting on closed. To be double sure if i have in my numerator column 1,5,7 the sum to be used is 13 and numerator_sum_squares_column would be 1+25+49=75 right?

**Comment by iampelle** [comment]
Yes, exactly. You can also find the formula under Definition on the [Wikipedia page for variance](https://en.m.wikipedia.org/wiki/Variance). "In other words, the variance of X is equal to the mean of the square of X minus the square of the mean of X."
